name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          printf"%s" "$SSH_PRIVATE_KEY" > ~/.ssh/private.key  # Add the SSH private key to a file
          chmod 600 ~/.ssh/private.key  # Set the correct permissions for the private key
          eval $(ssh-agent -s)  # Start the SSH agent
          ssh-add ~/.ssh/private.key  # Add the private key to the SSH agent
          ssh -T ubuntu@${{ secrets.EC2_PUBLIC_IP }}

      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh  # Ensure the .ssh directory exists
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts  # Add the EC2 public IP to known hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'cd /home/ubuntu/my-app && git pull && npm install && pm2 restart my-app'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Pass the private key from secrets
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}  # Pass the EC2 IP address from secrets
