name: Node.js CI/CD

# Controls when the workflow will run
on:
  push:
    branches:
      - main  # Triggers only on the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main'

# The jobs to be run
jobs:
  # Job 1: Test
  test:
    runs-on: ubuntu-latest  # The operating system for the runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify Node.js version
      - name: Install dependencies
        run: npm install  # Run npm install to set up dependencies
      - name: Run tests
        run: npm test  # Run the test script defined in package.json

  # Job 2: Deploy (example for deploying to AWS EC2)
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure tests pass before deploying
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV  # Change region if needed

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli  # Install AWS CLI

      - name: Deploy to EC2 using AWS CLI
        run: |
          # Configure AWS CLI with the environment variables
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION
          
          # SSH into EC2 and run deployment commands
          ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-ip << 'EOF'
            cd /path/to/your/app
            git pull
            npm install
            npm start
          EOF
