name: Node.js CI/CD on Amazon Linux

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Checkout the code from the repo

    - name: Install dependencies
      run: npm install  # Install Node.js dependencies

    - name: Deploy to AWS EC2
      uses: appleboy/scp-action@master  # Copy files to EC2 instance
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}  # EC2 Public IP from GitHub Secrets
        username: ubuntu  # Username for your EC2 instance
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key stored in GitHub Secrets
        source: "./"  # The source directory (current directory in your repo)
        target: "/home/ubuntu/myapp"  # Target directory on your EC2 instance

    - name: Restart Node.js application
      uses: appleboy/ssh-action@master  # SSH into EC2 and restart application
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}  # EC2 Public IP from GitHub Secrets
        username: ubuntu  # Username for your EC2 instance
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key stored in GitHub Secrets
        script: |
          cd /home/ubuntu/myapp  # Navigate to the application directory
          git pull  # Pull the latest changes from the repository
          npm install  # Ensure dependencies are up to date
          pm2 restart myapp || npm start  # Restart the app with PM2 or directly with npm start
